name: Automatic Infra-scripts Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    uses: Aventus-Network-Services/Infra-scripts/.github/workflows/automatic-releases.yaml@v5.1.0
    with:
      default_bump: patch
    secrets:
      envPat: ${{ secrets.GITHUB_TOKEN }}
